name: med_g
description: Medical Consulting Mobile Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  shared_preferences: ^2.0.12
  easy_localization: ^3.0.0
  get_it: ^7.2.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.4+5
  keyboard_dismisser: ^2.0.0
  flutter_calendar_carousel: ^2.1.0
  pin_code_fields: ^7.3.0
  mask_text_input_formatter: ^2.1.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  onesignal_flutter: ^3.2.8
  flutter_launcher_icons: ^0.9.2
  formz: ^0.4.1
  cached_network_image: ^3.2.0
  jiffy: ^5.0.0
  shimmer: ^2.0.0
  flutter_cupertino_datetime_picker:
    git:
      url: https://github.com/AbuAbdulloh/flutter_cupertino_datetime_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  lints: ^1.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icons/med_g_logo.png"
  adaptive_icon_background: "assets/launcher_icons/background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/onboarding/
    - assets/icons/global/
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - assets/launcher_icons/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/Barlow-Black.ttf
        - asset: assets/fonts/Barlow-BlackItalic.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow-BoldItalic.ttf
        - asset: assets/fonts/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow-ExtraBoldItalic.ttf
        - asset: assets/fonts/Barlow-ExtraLight.ttf
        - asset: assets/fonts/Barlow-ExtraLightItalic.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
        - asset: assets/fonts/Barlow-Light.ttf
        - asset: assets/fonts/Barlow-LightItalic.ttf
        - asset: assets/fonts/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow-MediumItalic.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow-SemiBoldItalic.ttf
        - asset: assets/fonts/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow-ThinItalic.ttf
